package com.qzzx.android.paroute.utils;

/**
 * Created by Administrator on 2018/8/6 0006.
 */

public class Constant {


    // Generate


    // Generate
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "ARouter";
    public static final String TAG = PROJECT + "::";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY AROUTER.";
    public static final String METHOD_LOAD_INTO = "loadInto";
    public static final String METHOD_INJECT = "inject";
    public static final String NAME_OF_ROOT = PROJECT + SEPARATOR + "Root";
    public static final String NAME_OF_PROVIDER = PROJECT + SEPARATOR + "Providers";
    public static final String NAME_OF_GROUP = PROJECT + SEPARATOR + "Load123" + SEPARATOR;
    public static final String NAME_OF_INTERCEPTOR = PROJECT + SEPARATOR + "Interceptors";
    public static final String NAME_OF_AUTOWIRED = SEPARATOR + PROJECT + SEPARATOR + "Autowired";
    public static final String PACKAGE_OF_GENERATE_FILE = "com.qzzx.android.paroute.routes";


    // Custom interface
    private static final String FACADE_PACKAGE = "com.qzzx.android.paroute.appearance";
    private static final String TEMPLATE_PACKAGE = ".template";

    public static final String IROUTERROOT = FACADE_PACKAGE + TEMPLATE_PACKAGE + ".IRouterRoot";

    // Options of processor
    public static final String KEY_MODULE_NAME = "moduleName";

    // System interface
    public static final String ACTIVITY = "android.app.Activity";

    // Options of processor

}
